import { createCapitals } from './helpers/createCapitals';
import { DIFFICULTY as Difficulty } from './types';

export default [
  // Ənlər
  {
    field: 1,
    subfield: 1,
    title: 'Yer kürəsinin ərazisinə görə ən böyük ölkəsi hansıdır?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.SUPER_EASY,
    answers: ['rusya', 'rusiya', 'rusia'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Ən çox əhalisi olan ölkə hansıdır?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.SUPER_EASY,
    answers: ['chin', 'çin', 'cin'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Yer kürəsinin ən hündür dağı hansıdır?',
    description: 'Dağın adını yazın',
    difficulty: Difficulty.SO_EASY,
    answers: ['comolonqma', 'comulunqma', 'comolunqma', 'everest', 'everes'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Yer kürəsinin ən dərin gölü hansıdır?',
    description: 'Gölün adını yazın',
    difficulty: Difficulty.EASY,
    answers: ['baykal', 'baikal'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Afrikanın ən uzun çayı hansıdır?',
    description: 'Çayın adını yazın',
    difficulty: Difficulty.SO_EASY,
    answers: ['nil'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Afrikanın ən uzun ikinci çayı hansıdır?',
    description: 'Çayın adını yazın',
    difficulty: Difficulty.MEDIUM_EASY,
    answers: ['konqo', 'konqo çayı', 'congo', 'kongo', 'konqo cayi'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Yer kürəsinin ərazisinə görə ən kiçik ölkəsi?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.SO_EASY,
    answers: ['vatikan', 'vatkan'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Afrikanın ən hündür dağı hansıdır?',
    description: 'Dağın adını yazın',
    difficulty: Difficulty.MEDIUM_EASY,
    answers: ['klimanjaro', 'klimancaro', 'kilimancaro'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Kanadanın ən hündür dağı hansıdır?',
    description: 'Dağın adını yazın',
    difficulty: Difficulty.HARD,
    answers: ['logan', 'loqan', 'loqan dağı', 'loqan dagi'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Kanarya adaları hansı ölkənin tabeliyindədir?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.HARD,
    answers: ['spain', 'ispaniya', 'ispanya', 'spaniya', 'ıspaniya', 'ıspanya'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Sahili olmayan yeganə dəniz hansıdır?',
    description: 'Dənizin adını yazın',
    difficulty: Difficulty.MEDIUM_HARD,
    answers: ['sargasso', 'sargass', 'sargas', 'sarqas', 'sarqaso', 'sarqass'],
  },
  // Paytaxtlar
  ...createCapitals([
    {
      title: 'Azərbaycanın',
      difficulty: Difficulty.SUPER_EASY,
      answers: ['baki', 'baku', 'bakı'],
    },
    {
      title: 'Rusya federasiyasının',
      difficulty: Difficulty.SUPER_EASY,
      answers: ['maskva', 'moskva', 'moskova'],
    },
    {
      title: 'Türkiyənin',
      difficulty: Difficulty.SUPER_EASY,
      answers: ['ankara', 'anqara'],
    },
    {
      title: 'İran İR-ın',
      difficulty: Difficulty.SO_EASY,
      answers: ['tehran'],
    },
    {
      title: 'Fransanın',
      difficulty: Difficulty.SO_EASY,
      answers: ['parij', 'paris'],
    },
    {
      title: 'Almaniyanın',
      difficulty: Difficulty.SO_EASY,
      answers: ['berlin'],
    },
    {
      title: 'Kanadanın',
      difficulty: Difficulty.EASY,
      answers: ['ottava', 'otava', 'otdava'],
    },
    {
      title: 'Pakistanın',
      difficulty: Difficulty.EASY,
      answers: ['islamabad', 'ıslamabad'],
    },
    {
      title: 'İspaniyanın',
      difficulty: Difficulty.EASY,
      answers: ['madrid', 'madrit'],
    },
    {
      title: 'Kosovanın',
      difficulty: Difficulty.MEDIUM_HARD,
      answers: ['prisdina', 'pristina'],
    },
    {
      title: 'Salvadorun',
      difficulty: Difficulty.MEDIUM_EASY,
      answers: ['san salvador', 'san-salvador', 'sansalvador'],
    },
    {
      title: 'Toqonun',
      difficulty: Difficulty.HARD,
      answers: ['lome'],
    },
    {
      title: 'Beninin',
      difficulty: Difficulty.HARD,
      answers: [
        'port novo',
        'porto novo',
        'portnovo',
        'portonovo',
        'port-novo',
        'porto-novo',
        'port nova',
        'porto nova',
        'portnova',
        'portonova',
        'port-nova',
        'porto-nova',
      ],
    },
    {
      title: 'Surinamın',
      difficulty: Difficulty.SO_HARD,
      answers: ['paramaribo', 'paramariba', 'paramarbo', 'paramarba'],
    },
    {
      title: 'Laosun',
      difficulty: Difficulty.SO_HARD,
      answers: ['vientian', 'vientiane', 'vientiyane', 'viyentiyane', 'vientiyan', 'viyentiyan'],
    },
    {
      title: 'Tonqanın',
      difficulty: Difficulty.SO_HARD,
      answers: ['nukualofa', "nuku'alofa", 'nuku alofa', 'nuku-alofa'],
    },
    {
      title: 'Sent-Vinsentin',
      difficulty: Difficulty.SO_HARD,
      answers: [
        'kinqstaun',
        'kinqstoun',
        'kinqstavn',
        'kinqstovn',
        'kingstaun',
        'kingstoun',
        'kinqston',
        'kinqstan',
        'kingstown',
      ],
    },
    {
      title: 'Efiopiyanın',
      difficulty: Difficulty.MEDIUM_EASY,
      answers: [
        'addis ababa',
        'addisababa',
        'addis-ababa',
        'əddis əbəbə',
        'əddisəbəbə',
        'əddis-əbəbə',
        'eddis ebebe',
        'eddisebebe',
        'eddis-ebebe',
      ],
    },
    {
      title: 'Yeni Kaledoniyanın',
      difficulty: Difficulty.SUPER_HARD,
      answers: ['noumea', 'nouméa', 'noumeya', 'nouméya', 'nomea', 'nomeya', 'numea', 'numeya'],
    },
  ]),
  {
    field: 1,
    subfield: 1,
    title: 'Rusyada neçə saat qurşağı var?',
    description: 'Ədədi yazın',
    difficulty: Difficulty.MEDIUM_EASY,
    answers: ['11', 'onbir', 'on bir'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Cənubi Amerika materikinin cənub-qərbi boyunca uzanan dağ silsiləsinin adı?',
    description: 'Silsilənin adını yazın',
    difficulty: Difficulty.MEDIUM_EASY,
    answers: [
      'and',
      'ant',
      'and dağları',
      'and silsiləsi',
      'ant silsiləsi',
      'ant silsiləsi',
      'and daglari',
      'ant daglari',
      'and silsilesi',
      'ant silsilesi',
    ],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Həm ekvator xəttinin, həm də qrinviç meridianının kəsdiyi Afrika ölkəsi hansıdır?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.HARD,
    answers: ['qabon', 'gabon'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'ABŞ-ın neçə saat qurşağı var?',
    description: 'Ədədi yazın',
    difficulty: Difficulty.MEDIUM,
    answers: ['6', 'altı', 'alti'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Amerika qitəsinin ən quraq səhrası hansıdır?',
    description: 'Səhranın adını yazın',
    difficulty: Difficulty.MEDIUM_EASY,
    answers: ['atakama səhrası', 'atakama sehrasi', 'atakama', 'atacama'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Ən uzun sahil xəttinə sahib olan ölkə?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.MEDIUM,
    answers: ['kanada', 'kanata'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Bermuda üçbucağı hansı okeanda yerləşir?',
    description: 'Okeanı yazın',
    difficulty: Difficulty.MEDIUM_EASY,
    answers: ['atlantik', 'atlantiq'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Hansı ölkəni Holland Qayanası adlandırırlar?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.HARD,
    answers: ['sürinam', 'surinam'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Hindistanda yerləşən ən hündür dağ hansıdır?',
    description: 'Dağın adını yazın',
    difficulty: Difficulty.SUPER_HARD,
    answers: ['kançencaqra', 'kancencaqra'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Haiti respublikası hansı adanın içində yerləşir?',
    description: 'Adanın adını yazın',
    difficulty: Difficulty.HARD,
    answers: ['ispanyola', 'hispanyola', 'hispanola', 'hispaniola', 'ispaniola'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Ekvator xətti neçə müstəqil ölkəni kəsir?',
    description: 'Ədədi yazın',
    difficulty: Difficulty.HARD,
    answers: ['13', 'thirteen', 'onüç', 'onuc', 'on üç', 'on uc'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Ən çox saat qurşağına sahib olan ölkə hansıdır?',
    description: 'Ölkənin adını yazın',
    difficulty: Difficulty.HARD,
    answers: ['fransa', 'france'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Afrikanın neçə ölkəsinin okeana birbaşa çıxışı yoxdur?',
    description: 'Ədədi yazın',
    difficulty: Difficulty.SUPER_HARD,
    answers: ['sixteen', '16', 'onaltı', 'onalti', 'on alti', 'on altı'],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Yer kürəsində ən şimalda yerləşən şəhər hansıdır?',
    description: 'Şəhərin adını yazın',
    difficulty: Difficulty.SUPER_HARD,
    answers: [
      'longyearbyen',
      'lonqyirbyuen',
      'lonqyirbyen',
      'lonqyirbuen',
      'lonqirbyuen',
      'lonqyrbuen',
    ],
  },
  {
    field: 1,
    subfield: 1,
    title: 'Yer kürəsinin ən hündür ikinci dağı hansıdır?',
    description: 'Dağın adını yazın',
    difficulty: Difficulty.MEDIUM_EASY,
    answers: [
      'k2',
      'k 2',
      'ka2',
      'ka 2',
      'k iki',
      'ka iki',
      'çoqori',
      'coqori',
      'cogori',
      'çogori',
      'choqori',
      'chogori',
      'dapsanq',
      'dapsang',
      'dapsank',
      'qoduin osten',
      'qoduin-osten',
      'qoduinosten',
    ],
  },
];
